name: jd_check_in

on: 
  workflow_dispatch:
  schedule:
    - cron: "8 16 * * *"
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
        
      - name: prepare node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: run job
        #run: |
          #npm install request
          #wget -q -O - https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js | cat | sed -e "s@var Key = ''@var Key = '${{ secrets.jd_key1 }}'@g" | node | cat
          #wget -q -O - https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js | cat | sed -e "s@var Key = ''@var Key = '${{ secrets.jd_key2 }}'@g" | node | cat
        run: |
          npm install request
          wget -q -O - https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js | cat | node > jd.log
          grep -q "京东签到" jd.log
