name: jd_check_in

on: 
  workflow_dispatch:
  schedule:
    - cron: "8 16 * * *"
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v2
        
      - name: prepare node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: run job
        run: |
          npm install request
          wget -q -O - https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js | cat | sed -e "s@var Key = ''@var Key = '${{ secrets.jd_key1 }}'@g" | sed -e "s@var DualKey = ''@var DualKey = '${{ secrets.jd_key2 }}'@g" | node > jd.log
          val1=$(grep "${{ secrets.MATCHED1 }}" jd.log | wc -l)
          val2=$(grep "${{ secrets.MATCHED2 }}" jd.log | wc -l)
          echo "::set-output name=matched1::${val1}"
          echo "::set-output name=matched2::${val2}"
        id: jd
      
      - name: Send mail
        if: steps.jd.outputs.matched1 == 0 || steps.jd.outputs.matched2 == 0
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: JD Checkin Status
          body: file://jd.log
          to: ${{secrets.RECEIVER}}
          from: Github Actions
          content_type: text/html
