name: Start

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install deps
      run: | 
        npm install -g heroku
        heroku --version

    - name: Scaling1
      run: |
       touch result.txt
       HEROKU_API_KEY=${{ secrets.heroku_key1 }} heroku ps:scale web=1 --app ${{ secrets.app1 }} > result.txt
       grep "1:Free" result.txt
       HEROKU_API_KEY=${{ secrets.heroku_key2 }} heroku ps:scale web=1 --app ${{ secrets.app2 }} > result.txt
       grep "1:Free" result.txt
       HEROKU_API_KEY=${{ secrets.heroku_key3 }} heroku ps:scale web=1 --app ${{ secrets.app3 }} > result.txt
       grep "2:Free" result.txt
