name: Start

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: AlexisMateo/sendmail-action@5
        with:
          smtp-server: ${{ secrets.SMTP_SERVER }}
          smtp-server-port: ${{ secrets.SMTP_SERVER_PORT }}
          auth-user: ${{ secrets.AUTH_USER }}
          auth-password: ${{secrets.EMAIL_PASSWORD }}
          subject: correciones a ${{github.repository}}
          body: ${{github.context.payload}}
          from: ${{ secrets.EMAIL_FROM }}
          to: ${{ secrets.EMAIL_RECIVER }}
          is-tls: false
          commit-message: true
      - run: npm install -g heroku
      - run: heroku --version
      - run: HEROKU_API_KEY=${{ secrets.heroku_key1 }} heroku ps:scale web=1 --app ${{ secrets.app1 }}
      - run: HEROKU_API_KEY=${{ secrets.heroku_key2 }} heroku ps:scale web=1 --app ${{ secrets.app2 }}
      - run: HEROKU_API_KEY=${{ secrets.heroku_key3 }} heroku ps:scale web=1 --app ${{ secrets.app3 }}
