name: Stop

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm install -g heroku
          heroku --version
          HEROKU_API_KEY=${{ secrets.heroku_key1 }} heroku ps:scale web=0 --app ${{ secrets.app1 }}
          HEROKU_API_KEY=${{ secrets.heroku_key2 }} heroku ps:scale web=0 --app ${{ secrets.app2 }}
          HEROKU_API_KEY=${{ secrets.heroku_key3 }} heroku ps:scale web=0 --app ${{ secrets.app3 }}
